function setForm(form) {
  // ...
  for(let i=QuestionLineEnum.MIN_LINE;i<=QuestionLineEnum.MAX_LINE;i++){
    // ...
    const questionGeneralFeedback = getCell(i,15).getValue();
    // ...
    const questionInfo = Object.create({
      // ...
      'questionGeneralFeedback':questionGeneralFeedback,
      // ...
    });
    // ... 
  }  
  // ...
}
