function setForm(form) {
  for(let i=QuestionLineEnum.MIN_LINE;i<=QuestionLineEnum.MAX_LINE;i++){
    // ...
    const questionCorrectAnswers = getCell(i,12).getValue(); 
    // ... 
    const questionInfo = Object.create({
      // ...
      'questionCorrectAnswers':questionCorrectAnswers, 
      // ...
    });
    // ...
  }
  // ...
}
